#!/usr/bin/env python3
"""Generate LocalReads project-review issue folders (ISSUE-001 .. ISSUE-032)."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

SCRIPT_DIR = Path(__file__).resolve().parent
ISSUES_ROOT = SCRIPT_DIR / "issues"

GITKEEP_LINE = "# Placeholder for issue screenshots (add PNGs when verifying fixes).\n"


def _table_row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def render_issue_md(issue: dict) -> str:
    related = ", ".join(f"ISSUE-{r}" for r in issue.get("related", [])) or "-"
    files = ", ".join(f"`{f}`" for f in issue["files"])
    lines = [
        f"# ISSUE-{issue['id']}: {issue['title']}",
        "",
        "| Field | Value |",
        "| --- | --- |",
        _table_row(["ID", f"ISSUE-{issue['id']}"]),
        _table_row(["Severity", issue["severity"]]),
        _table_row(["Status", "Open"]),
        _table_row(["Affected files", files]),
        _table_row(["Summary", issue["summary"]]),
        _table_row(["Related issues", related]),
        "",
    ]
    return "\n".join(lines)


def render_analysis_md(issue: dict) -> str:
    a = issue["analysis"]
    refs = "\n".join(f"- {r}" for r in a.get("code_refs", []))
    parts = [
        f"# Analysis - ISSUE-{issue['id']}",
        "",
        "## Root cause",
        a["root_cause"],
        "",
        "## Code references",
        refs,
        "",
        "## Impact",
        a["impact"],
        "",
        "## How to verify",
        a["verify"],
        "",
    ]
    return "\n".join(parts)


def render_fix_md(issue: dict) -> str:
    return f"# Proposed fix - ISSUE-{issue['id']}\n\n{issue['fix'].strip()}\n"


def render_resolution_md(issue: dict) -> str:
    r = issue["resolution"]
    steps = "\n".join(f"- [ ] {s}" for s in r["steps"])
    parts = [
        f"# Resolution plan - ISSUE-{issue['id']}",
        "",
        "## Next steps",
        steps,
        "",
        "## Estimated effort",
        r["effort"],
        "",
        "## Roadmap phase",
        r["phase"],
        "",
        "Status: Planned",
        "",
    ]
    return "\n".join(parts)


def _i(
    id_: str,
    severity: str,
    title: str,
    files: list[str],
    summary: str,
    related: list[str],
    root_cause: str,
    code_refs: list[str],
    impact: str,
    verify: str,
    fix: str,
    steps: list[str],
    effort: str,
    phase: str,
) -> dict:
    return {
        "id": id_,
        "severity": severity,
        "title": title,
        "files": files,
        "summary": summary,
        "related": related,
        "analysis": {
            "root_cause": root_cause,
            "code_refs": code_refs,
            "impact": impact,
            "verify": verify,
        },
        "fix": fix,
        "resolution": {"steps": steps, "effort": effort, "phase": phase},
    }


def build_registry() -> list[dict]:
    return [
        _i(
            "001",
            "HIGH",
            "Memory leaks from missing @implements IDisposable",
            ["LocalReads/Pages/SearchBooks.razor", "LocalReads/Layout/NavMenu.razor"],
            "Components subscribe to AppState/NotificationService events and define Dispose(), but Blazor never calls Dispose() without @implements IDisposable.",
            ["002", "008"],
            "SearchBooks and NavMenu wire handlers in OnInitialized(Async) and implement Dispose() without @implements IDisposable. NavMenu never unsubscribes NotificationService.OnNotificationReceived.",
            ["SearchBooks.razor subscriptions ~181-196", "NavMenu.razor UserState and NotificationService ~56-70"],
            "Handlers keep firing after navigation, causing extra renders and possible NullReferenceException on disposed instances.",
            "Navigate Home and Search Books repeatedly; log in Dispose() \u2014 without @implements IDisposable it never runs.",
            "Add `@implements IDisposable` at the top of both components.\n\n```razor\n@implements IDisposable\n```\n\nIn NavMenu `Dispose()`, also unsubscribe notifications:\n\n```csharp\nNotificationService.OnNotificationReceived -= StateHasChanged;\n```\n",
            ["Add @implements IDisposable", "Complete NavMenu unsubscribe", "Smoke-test navigation"],
            "15-30 minutes",
            "Phase 1 \u2014 Quick wins",
        ),
        _i(
            "002",
            "HIGH",
            "async void anti-pattern in TriggerReload",
            ["LocalReads/Pages/SearchBooks.razor"],
            "TriggerReload is async void but subscribed to SearchResults.OnBooksSearchChanged.",
            ["001", "009"],
            "Custom event handlers must return Task; async void swallows exceptions (~line 300).",
            ["SearchBooks.razor ~300 private async void TriggerReload()"],
            "Unhandled exceptions can fault WASM without UI feedback.",
            "Break reload in dev and compare async void vs async Task behavior.",
            "Use `async Task` instead of `async void`:\n\n```csharp\nprivate async Task TriggerReload()\n{\n    await InvokeAsync(async () =>\n    {\n        if (_table != null)\n        {\n            await _table.ReloadServerData();\n            StateHasChanged();\n        }\n    });\n}\n```\n",
            ["Change signature", "Match event delegate", "Regression-test search reload"],
            "10 minutes",
            "Phase 1 \u2014 Quick wins",
        ),
        _i(
            "003",
            "HIGH",
            "Authorization is inconsistent",
            ["LocalReads/App.razor", "LocalReads/Pages/Home.razor", "LocalReads/Pages/EditProfile.razor"],
            "Only EditProfile uses [Authorize]; other pages unguarded; NotAuthorized links use wrong routes.",
            ["004", "018", "023"],
            "AuthorizeRouteView exists but most pages omit @attribute [Authorize]. NotAuthorized links /users/login and /users/register instead of /login and /register.",
            ["App.razor NotAuthorized ~6-9", "EditProfile sole [Authorize]", "Home manual redirect"],
            "Logged-out users can open /mybooks and hit null UserState; auth links 404.",
            "Visit /mybooks logged out; click NotAuthorized Login link.",
            "Fix NotAuthorized URLs and adopt `[Authorize]` on protected pages:\n\n```razor\n@attribute [Authorize]\n@page \"/mybooks\"\n```\n",
            ["Fix App.razor links", "Add [Authorize]", "Remove Home redirect", "Test deep links"],
            "2-3 hours",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "004",
            "HIGH",
            "Unchecked HTTP responses",
            ["LocalReads/Pages/Home.razor", "LocalReads/Pages/ViewProfile.razor", "LocalReads/Pages/MyBooks.razor", "LocalReads/Pages/ViewBook.razor"],
            "Pages use HttpRequest.Get(...).Content without checking Success.",
            ["003", "012", "013"],
            "HttpResponse<T>.Success is ignored at Home, ViewProfile, MyBooks, ViewBook call sites.",
            ["Home.razor ~89-90", "ViewProfile ~61", "MyBooks ~121", "ViewBook ~105"],
            "API failures yield null Content and NullReferenceException in UI.",
            "Stop API and load Home \u2014 expect error message not crash.",
            "Check `Success` before using `Content`:\n\n```csharp\nif (!response.Success)\n{\n    Snackbar.Add(response.ErrorMessage ?? \"Request failed.\", Severity.Error);\n    return;\n}\n```\n",
            ["Audit HttpRequest usages", "Add guards", "Empty-state on error"],
            "Half day",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "005",
            "HIGH",
            "Hardcoded configuration",
            ["LocalReads/Program.cs", "LocalReads/Services/NotificationService.cs", "LocalReads/Layout/NavMenu.razor"],
            "API URL, SignalR hub, and profile link hardcoded for local dev / user id 1.",
            ["019"],
            "Program.cs BaseAddress localhost:5033; NotificationService hub localhost:7223; NavMenu NavigateTo /profile/1.",
            ["Program.cs ~15", "NotificationService.cs ~17-18", "NavMenu.razor ~81"],
            "Breaks non-local deployments; wrong profile opened from avatar.",
            "Change API port or click avatar \u2014 URL should use logged-in user id.",
            "Load API and SignalR URLs from configuration; use dynamic profile id in NavMenu:\n\n```csharp\nNavigation.NavigateTo($\"/profile/{AppState.UserState.User.Id}\");\n```\n",
            ["Add appsettings.json", "Wire Program and NotificationService", "Fix NavMenu profile"],
            "1-2 hours",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "006",
            "MEDIUM",
            "Duplicate AddMudServices",
            ["LocalReads/Program.cs"],
            "AddMudServices registered twice in Program.cs.",
            ["005"],
            "Two AddMudServices calls (~20 and ~26-37) may override MudBlazor options.",
            ["Program.cs duplicate AddMudServices"],
            "Unpredictable snackbar/dialog configuration.",
            "grep AddMudServices \u2014 should appear once with config.",
            "Remove first call; keep configured registration.",
            ["Remove duplicate", "Verify snackbar", "Rebuild client"],
            "10 minutes",
            "Phase 1 \u2014 Quick wins",
        ),
        _i(
            "007",
            "MEDIUM",
            "Dual token storage access",
            ["LocalReads/Services/AuthService.cs", "LocalReads/Services/HttpRequest.cs"],
            "Token written via Blazored LocalStorage, read via JS interop in HttpRequest.",
            ["023", "008"],
            "Same userState key accessed two different ways.",
            ["AuthService SetItemAsync", "HttpRequest.js ~213-221"],
            "Auth header may desync after storage changes.",
            "Login and inspect Authorization header on API calls.",
            "Single token API on IAuthService; remove JS read from HttpRequest.",
            ["Introduce token accessor", "Refactor HttpRequest", "Test 401 flow"],
            "2-3 hours",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "008",
            "MEDIUM",
            "NotifyAuthenticationStateChanged on every auth read",
            ["LocalReads/Services/CustomAuthStateProvider.cs"],
            "GetAuthenticationStateAsync notifies on every read.",
            ["001", "007"],
            "NotifyAuthenticationStateChanged inside GetAuthenticationStateAsync (~46).",
            ["CustomAuthStateProvider.cs ~46"],
            "Extra re-renders and possible UI flicker.",
            "Log notifications \u2014 should spike only on login/logout.",
            "Notify only when token/claims change.",
            ["Move notifications to login/logout", "Regression-test auth UI"],
            "1 hour",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "009",
            "MEDIUM",
            "Silent exception swallowing in search table",
            ["LocalReads/Pages/SearchBooks.razor"],
            "LoadServerData catch returns stale books silently.",
            ["002", "004"],
            "catch (Exception) at ~289-296 returns previous AppState books.",
            ["SearchBooks.razor ~289-296"],
            "Users see stale search results on API errors.",
            "Fail API during pagination \u2014 expect error not stale data.",
            "Snackbar on failure; return empty TableData or rethrow after notify.",
            ["Replace silent catch", "Log in dev", "Test failed search"],
            "30 minutes",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "010",
            "MEDIUM",
            "Pagination guard logic likely wrong",
            ["LocalReads/Pages/SearchBooks.razor"],
            "Page/search guard uses AND; unused _notShowPromptTwiceOnOverride.",
            ["009", "017"],
            "Guard ~276-281 likely needs OR; dead field ~179.",
            ["SearchBooks guard condition", "unused _notShowPromptTwiceOnOverride"],
            "Pagination prompts behave incorrectly.",
            "Change term and page rapidly \u2014 observe prompt logic.",
            "Fix boolean guard; remove or use dead state.",
            ["Document UX", "Fix guard", "Remove dead state", "Manual test"],
            "1-2 hours",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "011",
            "MEDIUM",
            "ViewBook list type not initialized",
            ["LocalReads/Pages/ViewBook.razor"],
            "_listType not set from Favorite.State after load.",
            ["004", "014"],
            "Defaults to WantToRead; not mapped after GET (~98, 105-110).",
            ["ViewBook.razor _listType and load path"],
            "Dropdown shows wrong shelf for in-progress books.",
            "Open in-progress favorite in ViewBook \u2014 select should match API.",
            "Set _listType from ServerBook.Favorite.State after load.",
            ["Map state after GET", "Verify binding", "Test list types"],
            "30 minutes",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "012",
            "MEDIUM",
            "Register page incomplete UX",
            ["LocalReads/Pages/RegisterPage.razor"],
            "No loading state, _error unused, button says Signing in....",
            ["004", "023"],
            "_isLoading never true; _error never set; wrong button copy.",
            ["RegisterPage.razor ~27-31 and ~59-67"],
            "No feedback on slow or failed registration.",
            "Invalid register and API down \u2014 expect spinner and errors.",
            "Mirror LoginPage: _isLoading, _error, Register/Registering... labels.",
            ["Wire loading", "Surface errors", "Fix button text"],
            "45 minutes",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "013",
            "MEDIUM",
            "EditProfile save feedback missing",
            ["LocalReads/Pages/EditProfile.razor"],
            "HandlUpdate ignores failures; empty success branch.",
            ["004", "026"],
            "No Success check; typo HandlUpdate.",
            ["EditProfile HandlUpdate"],
            "Users cannot tell if profile saved.",
            "Force API error on save \u2014 need snackbar feedback.",
            "Rename HandleUpdate; check Success; success/error snackbars.",
            ["Rename handler", "Add guards", "Snackbar feedback"],
            "30 minutes",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "014",
            "MEDIUM",
            "Duplicated favorite/progress logic",
            ["LocalReads/Pages/SearchBooks.razor", "LocalReads/Pages/Home.razor", "LocalReads/Pages/MyBooks.razor"],
            "Same dialog+API+snackbar flows copied across three pages.",
            ["011", "015", "016"],
            "~50+ lines duplicated per page instead of IFavoritesService.",
            ["SearchBooks, Home, MyBooks @code blocks"],
            "Fixes need triple application; behavior drift.",
            "Compare add-to-list on Home vs SearchBooks.",
            "Extract IFavoritesService / FavoritesService.",
            ["Design service", "Migrate pages", "Remove duplicates"],
            "1-2 days",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "015",
            "MEDIUM",
            "MyBooks table reload misuse",
            ["LocalReads/Pages/MyBooks.razor"],
            "Client Items table calls ReloadServerData on filter change.",
            ["014"],
            "MudTable bound to _favorites but uses server reload API.",
            ["MyBooks.razor table vs ReloadServerData"],
            "Reload no-op or inconsistent refresh.",
            "Change category \u2014 favorites should reload via HTTP not ServerData API.",
            "Use LoadFavoritesAsync or switch to ServerData model.",
            ["Pick table model", "Fix handler", "Test filters"],
            "1 hour",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "016",
            "MEDIUM",
            "Dead/broken BookCard",
            ["LocalReads/Components/BookCard.razor"],
            "Unreferenced component; broken menu handlers; hardcoded InProgress.",
            ["014", "017", "022"],
            "Not used; all menu items same handler; state hardcoded.",
            ["BookCard.razor \u2014 zero references"],
            "Dead code confuses maintenance.",
            "Find references to BookCard \u2014 none.",
            "Delete or fix handlers and integrate with pages.",
            ["Decide remove vs fix", "Fix menus", "Remove hardcoded state"],
            "1-2 hours",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "017",
            "MEDIUM",
            "Unused GoToBook in SearchBooks",
            ["LocalReads/Pages/SearchBooks.razor"],
            "GoToBook never called; links use MudLink directly.",
            ["010", "016"],
            "Private GoToBook ~312-315 unused.",
            ["SearchBooks.razor GoToBook method"],
            "Dead code noise in 317-line page.",
            "grep GoToBook \u2014 only definition.",
            "Remove method or use for row navigation consistently.",
            ["Remove or wire GoToBook", "Align link pattern"],
            "15 minutes",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "018",
            "MEDIUM",
            "Logout link navigation race",
            ["LocalReads/Layout/NavMenu.razor"],
            "Anchor href=/ with @onclick LogOut may navigate before async logout completes.",
            ["003", "007"],
            "`<a href=\"/\" @onclick=\"LogOut\">` races default navigation vs await LogOut.",
            ["NavMenu.razor ~46-47"],
            "Session may clear after navigation; stale auth UI.",
            "Click logout rapidly \u2014 token may remain briefly.",
            "Use MudButton or @onclick:preventDefault on anchor; await LogOut then NavigateTo.",
            ["Prevent default nav", "Await logout", "Verify token cleared"],
            "30 minutes",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "019",
            "MEDIUM",
            "Missing static assets",
            ["LocalReads/wwwroot"],
            "Referenced images missing under wwwroot.",
            ["005", "020"],
            "staticfiles/icon-logo.png, userprofile.png, images/placeholder-book.png absent.",
            ["wwwroot asset references in layout/pages"],
            "Broken images in UI.",
            "Load app \u2014 404 for image URLs in network tab.",
            "Add assets or update paths to existing files.",
            ["Inventory references", "Add or fix paths", "Visual check"],
            "1 hour",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "020",
            "MEDIUM",
            "Home book links to / instead of viewbook",
            ["LocalReads/Pages/Home.razor"],
            "Book titles link to home rather than /viewbook/{id}.",
            ["019", "022"],
            "MudLink Href=\"/\" ~20-24 instead of viewbook route.",
            ["Home.razor book title links"],
            "Users cannot open book detail from dashboard.",
            "Click title on Home \u2014 should open ViewBook.",
            "Href=$\"/viewbook/{googleBookId}\"",
            ["Fix links", "Test navigation"],
            "15 minutes",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "021",
            "MEDIUM",
            "MyServer back button inert",
            ["LocalReads/Pages/MyServer.razor"],
            "Back button has no OnClick handler.",
            ["022"],
            "MudButton back control ~line 8 without handler.",
            ["MyServer.razor ~8"],
            "Back affordance does nothing.",
            "Click back on MyServer \u2014 no navigation.",
            "OnClick NavigateTo prior page or /mybooks.",
            ["Add handler", "Test navigation"],
            "15 minutes",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "022",
            "MEDIUM",
            "Stub UI with no handlers",
            ["LocalReads/Pages/MyBooks.razor", "LocalReads/Pages/ViewBook.razor"],
            "Placeholder buttons (comments, edit activity) without handlers.",
            ["016", "020", "021"],
            "Add comment / Edit My Activity / Edit View buttons are stubs.",
            ["MyBooks and ViewBook placeholder actions"],
            "Users see non-functional controls.",
            "Click stub buttons \u2014 no action.",
            "Implement handlers or hide until ready.",
            ["Inventory stubs", "Implement or remove", "UX review"],
            "Half day",
            "Phase 3 \u2014 Maintainability",
        ),
        _i(
            "023",
            "MEDIUM",
            "AuthService login error handling incomplete",
            ["LocalReads/Services/AuthService.cs"],
            "Login errors not surfaced beyond bool; TODO at line 29.",
            ["003", "007", "012"],
            "AuthService returns false without detailed error propagation.",
            ["AuthService.cs ~29 TODO"],
            "Login failures show generic or no message.",
            "Wrong password login \u2014 user needs specific feedback.",
            "Return error message in result type; map API errors to UI.",
            ["Extend login result", "Update LoginPage", "Remove TODO"],
            "1-2 hours",
            "Phase 2 \u2014 Reliability",
        ),
        _i(
            "024",
            "LOW",
            "No PageTitle",
            ["LocalReads/Pages/*.razor"],
            "Routed pages lack PageTitle for browser tabs and a11y.",
            ["025", "032"],
            "Only NotFound sets title; pages omit <PageTitle>.",
            ["All Pages/*.razor except NotFound"],
            "Poor tab identification and screen reader context.",
            "Open tabs for Home vs Search \u2014 titles identical.",
            "Add <PageTitle>Name - LocalReads</PageTitle> per page.",
            ["Add titles to 9 pages", "Verify in browser tabs"],
            "30 minutes",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "025",
            "LOW",
            "FocusOnNavigate targets h1",
            ["LocalReads/App.razor"],
            "FocusOnNavigate Selector=h1 but pages use MudText not h1.",
            ["024", "032"],
            "App.razor ~11 FocusOnNavigate h1 mismatch.",
            ["App.razor FocusOnNavigate"],
            "Skip link / focus management ineffective.",
            "Navigate route \u2014 focus may not move to visible heading.",
            "Use semantic h1 per page or change selector to main landmark.",
            ["Add h1 or adjust FocusOnNavigate", "Keyboard test"],
            "30 minutes",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "026",
            "LOW",
            "Inconsistent naming",
            ["LocalReads/**/*.razor", "LocalReads/**/*.cs"],
            "Mixed naming: HandlUpdate, AfirmativeText, isLoading vs _isLoading.",
            ["013", "027"],
            "Typos and inconsistent field prefixes across codebase.",
            ["EditProfile HandlUpdate", "GenericDialog AfirmativeText", "Register isLoading"],
            "Harder code search and reviews.",
            "grep HandlUpdate and AfirmativeText.",
            "Rename to HandleUpdate, AffirmativeText; standardize _private fields.",
            ["Fix typos", "Naming pass in touched files"],
            "1 hour",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "027",
            "LOW",
            "SearchBox UX inconsistency",
            ["LocalReads/Components/SearchBox.razor"],
            "Raw HTML input vs MudBlazor elsewhere; weak keyboard/a11y.",
            ["026", "032"],
            "SearchBox uses plain input and emoji button without Enter or aria-label.",
            ["SearchBox.razor markup"],
            "Inconsistent UX and accessibility vs MudTextField pages.",
            "Tab to search \u2014 no Enter submit; compare to Mud forms.",
            "MudTextField with @onkeydown Enter; aria-label on search.",
            ["Replace input with MudTextField", "Enter key", "aria-label"],
            "1 hour",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "028",
            "LOW",
            "No CSS isolation",
            ["LocalReads/Pages/*.razor"],
            "No .razor.css files; mix of app.css and inline style blocks.",
            ["029"],
            "Per-page style blocks in Home, SearchBooks, MyServer only.",
            ["Home/SearchBooks/MyServer style blocks"],
            "Styles can leak globally.",
            "Inspect scoped attributes \u2014 none on components.",
            "Migrate inline styles to Component.razor.css files.",
            ["Pick pilot page", "Create .razor.css", "Remove inline blocks"],
            "Half day",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "029",
            "LOW",
            "Package version skew",
            ["LocalReads/LocalReads.csproj"],
            "Mixed 8.x WASM/Authorization with SignalR 9.x.",
            ["028"],
            "NuGet versions not aligned across Microsoft packages.",
            ["LocalReads.csproj PackageReference versions"],
            "Subtle compatibility warnings or build issues.",
            "dotnet list package --outdated on LocalReads.",
            "Align SignalR and components to same major (8.x).",
            ["Audit packages", "Bump consistently", "Rebuild"],
            "30 minutes",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "030",
            "LOW",
            "No frontend tests",
            ["LocalReads/"],
            "No bUnit, Playwright, or test project for WASM client.",
            ["031"],
            "Solution lacks frontend test coverage.",
            ["Solution structure \u2014 no *Tests* for Blazor"],
            "Regressions caught only manually.",
            "Search for bUnit/Playwright \u2014 none.",
            "Add bUnit project; tests for dialogs and auth guard.",
            ["Create test project", "Sample bUnit tests", "CI hook"],
            "1-2 days",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "031",
            "LOW",
            "Nullable reference gaps",
            ["LocalReads/State/SearchResults.cs", "LocalReads/State/UserState.cs"],
            "Nullable enabled but key state properties not initialized.",
            ["030"],
            "SearchResults and UserState properties may be null at runtime.",
            ["SearchResults.cs", "UserState.cs"],
            "Nullable warnings suppressed; null surprises in UI.",
            "Build with warnings as errors \u2014 check state types.",
            "Initialize properties or mark required; use null-forgiving only where safe.",
            ["Fix state models", "Resolve nullable warnings"],
            "1-2 hours",
            "Phase 4 \u2014 Quality",
        ),
        _i(
            "032",
            "LOW",
            "Minimal accessibility",
            ["LocalReads/Pages/*.razor", "LocalReads/Components/*.razor"],
            "Icon buttons rely on tooltip only; missing AriaLabel in places.",
            ["024", "025", "027"],
            "MudIconButton without AriaLabel; SearchBox lacks labels.",
            ["Icon actions across pages"],
            "Screen reader users get insufficient names.",
            " axe or manual screen reader on search and favorites actions.",
            "Add AriaLabel to icon buttons; ensure visible text or labels.",
            ["Audit icon buttons", "Add AriaLabel", "Retest with NVDA"],
            "Half day",
            "Phase 4 \u2014 Quality",
        ),
    ]


REGISTRY = build_registry()


def generate_all() -> int:
    count = 0
    for issue in REGISTRY:
        folder = ISSUES_ROOT / f"ISSUE-{issue['id']}"
        shots = folder / "screenshots"
        shots.mkdir(parents=True, exist_ok=True)
        files = {
            folder / "issue.md": render_issue_md(issue),
            folder / "analysis.md": render_analysis_md(issue),
            folder / "fix.md": render_fix_md(issue),
            folder / "resolution.md": render_resolution_md(issue),
            shots / ".gitkeep": GITKEEP_LINE,
        }
        for path, content in files.items():
            path.write_text(content, encoding="utf-8")
            count += 1
    return count


if __name__ == "__main__":
    total = generate_all()
    print(f"Generated {total} files across {len(REGISTRY)} issues.")
